spring:
  application:
    name: sob-blog-system

  datasource:
    url: jdbc:mysql://localhost:3306/sob_blog?characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 2773207p

server:
  port: 2020
